# Configuracion para H2 (local)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

# ============================================
# Configuracion para PostgreSQL (VPS)
# ============================================
spring.datasource.url=jdbc:postgresql://82.208.23.125:8090/archiveflow
spring.datasource.username=EAM
spring.datasource.password=eam10292398
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true

# ============================================
# Base ? Seleccionar perfil activo
# ============================================
spring.application.name=gestor

# Cambiar a 'tester' para pruebas
spring.profiles.active=dev

server.port=8080
server.servlet.context-path=/gestor
