# ============================================
# Perfil: DEV ? PostgreSQL en VPS
# ============================================

# Datasource
spring.datasource.url=jdbc:postgresql://82.208.23.125:8090/archiveflow
spring.datasource.username=EAM
spring.datasource.password=eam10292398
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.tuempresa.gestor=DEBUG
logging.level.org.springframework.web=DEBUG

# Swagger habilitado
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Mostrar errores completos
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param