create table if not exists users (
    id bigint generated by default as identity primary key,
    names varchar(255) not null,
    last_names varchar(255),
    email varchar(255),
    password varchar(255),
    phone varchar(255),
    user_role varchar(255),
    status boolean,
    created_date timestamp,
    updated_date timestamp
);

create table if not exists folder (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description varchar(255),
    active boolean,
    created_at timestamp,
    updated_at timestamp,
    user_id bigint not null,
    constraint fk_folders_user foreign key (user_id) references users(id)
);

create table if not exists document_type (
    id_type bigint generated by default as identity primary key,
    name varchar(255) not null,
    is_global boolean,
    active boolean,
    created_at timestamp,
    updated_at timestamp,
    user_id bigint,
    constraint fk_document_types_user foreign key (user_id) references users(id)
);

create table if not exists document (
    id_document bigint generated by default as identity primary key,
    title varchar(255),
    description varchar(255),
    file_path varchar(255),
    file_type varchar(255),
    file_size bigint,
    active boolean,
    observation varchar(255),
    created_date timestamp,
    updated_date timestamp,
    id_folder bigint not null,
    created_by bigint,
    id_type bigint,
    constraint fk_documents_folder foreign key (id_folder) references folders(id),
    constraint fk_documents_user foreign key (created_by) references users(id),
    constraint fk_documents_type foreign key (id_type) references document_types(id_type)
);

